version: '3.8'
services:
  translator:
    image: translator:latest
    container_name: translator
    build: .
    working_dir: /app
    ports:
      - 7860:7860
    volumes:
      - .:/app
    command: ["python", "app.py"]